# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
#  -----------------------------------------------------------------------------
#  Template: provider.tf
#
#  Description: This template defines the target AWS account info. Please Do NOT
#               modify this manually, this is autogenerated by terragrunt.
#  -----------------------------------------------------------------------------
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
  required_version = ">= 1.0"
}


provider "aws" {
  region = "ap-southeast-2"
}
